spring:
  application:
    name: view-controller

logging:
  level:
    org:
      springframework: INFO
      springframework.security: INFO


db:
  host: 127.0.0.1
  port: 5432
  name: tutor_finder_db
  user: postgres
  password: postgres

jwt:
  secretKey: m9sN9kRkJhEFlVCOp02sAh3G09IWY8krveQxnfyaHjY=
  minutesValid: 5
